### ISSUE TITLE
startup.sh中的下载链接404

### ISSUE THREAD

**Issue by AYSHSTUDIO** [ZingerLittleBee/server_bee-backend#105]
https://db.serverbee.app/cli//serverbee-web-x86_64-unknown-linux-musl.zip

**Comment by AYSHSTUDIO** [comment]
steam@l4d2:~$ HTTPS_PROXY=https://192.168.1.71:7897 bash startup.sh
OS: Linux
Architecture: AMD
=======================  Commands  ==========================
Welcome to use ServerBee automatic installation, please select an option:
1) Installation
2) Update
3) Uninstallation
4) Log
5) Stop
6) Exit
#? 1
=======================  Installation  ==========================
Starting installation...
Getting the latest version of ServerBee
Latest version:

Press Enter to install , or Ctrl+C to cancel

Downloading https://db.serverbee.app/cli//serverbee-web-x86_64-unknown-linux-musl.zip
mkdir: cannot create directory ‘serverbee’: File exists
unzip:  cannot find or open serverbee-web.zip, serverbee-web.zip.zip or serverbee-web.zip.ZIP.
rm: cannot remove 'serverbee-web.zip': No such file or directory

**Comment by ZingerLittleBee** [comment]
看样子是脚本没有拼接上版本号
