### ISSUE TITLE
Web的Terminal字体问题

### ISSUE THREAD

**Issue by peter5842** [ZingerLittleBee/server_bee-backend#63]
请问，这个字体是设置为服务端支持的呢？还是有哪些选项可以选择，已翻阅文档与github，未找到相关描述，因为我使用了oh-my-zsh以及p10k，所以需要设置字体，如能回答，十分感谢！

**Comment by ZingerLittleBee** [comment]
字体需要电脑已安装，并且浏览器中设置。
目前发现在 windows 系统中显示有 bug，字体会被拉长，近期会有更新解决这个问题，
并且将支持 windows 系统命令行。

**Comment by ZingerLittleBee** [comment]
c6955d6d0ea5a125e18b3ff97e9236acba9c2b5b
