### ISSUE TITLE
Failed to connect to localhost port 9527: Connection refused

### ISSUE THREAD

**Issue by 305507001** [ZingerLittleBee/server_bee-backend#74]
为什么命令安装完容器后，启动容器提示docker api失败，后台键入curl http://localhost:9527/local/config/app提示连接被拒绝

**Comment by ZingerLittleBee** [comment]
服务没启动吧，查看下 serverbee 目录下日志

**Comment by 305507001** [comment]
Error response from daemon: Bind mount failed: '/volume2/docker/ServerBeecon' does not exists. 这个是docker日志报错，是我路径绑定的不正确嘛
docker run -d \
  -v /proc:/proc \
  -v /dev:/dev \
  -v /sys:/sys \
  -v /etc:/etc \
  -v /volume2/docker/ServerBee:/volume2/docker/ServerBee \
  -v /volume2/docker/ServerBeecon:/volume2/docker/ServerBeecon \
  -v /usr/lib:/usr/lib \
  --privileged=true \
  --restart unless-stopped \
  --network=host \
  --name=serverbee-web \
  zingerbee/serverbee-web -p 9527
小白不是很懂
